### ISSUE TITLE
Latest volumio version broke plugin

### ISSUE THREAD

**Issue by Alien8ions** [Saiyato/volumio-audiophonicsonoff-plugin#2]
Hi
Don't know if this is the correct place to report an issue....

The latest volumio version
2.413 (21-06-2018)
FIXES
System will survive a plugin crashing on start

Simply states "the plugin did not start"
While the previous one made your plugin work as advertised.

Fwiw rpi 2.3 and audiophonics dac amp and atx board.

Unfortunately I'm not so well versed in programming so it's hard to debug it.
It would appear that the whole "let's make the plugins only usable from our repository " thing is a bit slow to say the least. The hardware is available for more than a year now but still no plugin in volumio for it although it is listed on the volumio forums plugins list...

Diego

**Comment by Saiyato** [comment]
Hi,

Yeah, the plugin is not yet hosted in the store, the store will contain all modules needed for post-2.411 versions of Volumio. I can create a custom package for post-2.411 versions... but I'm not sure this will really help.

The PR has been created, so I need to wait for Volumio to accept them. I might look into creating separate PR's for the different plugins to speed things up.

**Comment by Alien8ions** [comment]
Hi
Thanks for the reply

However I'm not sure I fully understand what you are saying.

It might take a while before it's available as intended by the main developer?

So for now the only workaround is installing the required scripts manually outside volumio's control, basically rendering the whole plugin thing a moot point... If it takes too long no one will take time to add the plugins to the store anyway.

Diego

**Comment by Saiyato** [comment]
Hi Diego,

This is a risk indeed, I can't change how this store thing works, but I did create separate PR's for the different plugins. The different PR's will make it easier for the Volumio team to check and approve small pieces of software.

The workaround is there for the developers, so they can't really disable that. For now however, yes, it's the only way to install the unsanctioned plugins.

Cheers

**Comment by Saiyato** [comment]
Btw, the step-by-step is as follows:

1. download the zip
2. unzip it
3. install build-essential (apt-get update && apt-get install -y build-essential)
4. execute "npm i" while in the directory
5. execute "volumio plugin install"

**Comment by Alien8ions** [comment]
Hi

I've tried to install the plugin on said version, using npm i but it still won't work..

Plugin failed to start....


npm rebuild did the trick though
So maybe this could be mentioned in the install notes...

Diego

**Comment by Saiyato** [comment]
Hi Diego,

I've installed it four times with npm i on my test machine, every time I reverted back to factory settings.
Can you confirm this happens every time in your machine? Otherwise I don't think it's wise to update the install notes based on one instance ;)

**Comment by Alien8ions** [comment]
True
Yet in my environment  (pi2, audiophonics dac amp & ATX board) the plugin installs and runs fine on volumio v 2.389.

I updated volumio to v 2.413 and the plugin no longer starts, a brief message is displayed.
The scripts no longer work, button led blinking rapidly and doesn't go on steadily.
edit: tried at least twice, with a sd card reflash as well

Checked the log files and luckily more info is given about node modules is the wrong version and npm rebuild or update (?, not sure about the latter) should be performed.
once that was done, all went as it should.

Diego

**Comment by audiomartin** [comment]
Hi there Saiyato,
I am running the marvelous Audiophonics ES9028 with Volumio. So far i made it working with all necessary plugins, Touchscreen, Q2M and AudiophonicsOnOff. Since the latest Volumio 2.457 it is impossible for me to install your Plugin. I tried as you recommend above, but can not get it working.
I did copy the zipped Plugin to /home/volumio/, then unzipped, went into folder folder and ran volumio install plugin...

```
volumio@volumio:~$ unzip volumio-audiophonicsonoff-plugin-master.zip 
Archive:  volumio-audiophonicsonoff-plugin-master.zip
9f20590e59d34379ed4fbc25454e76eab926e238
   creating: volumio-audiophonicsonoff-plugin-master/
  inflating: volumio-audiophonicsonoff-plugin-master/.gitattributes  
  inflating: volumio-audiophonicsonoff-plugin-master/LICENSE  
  inflating: volumio-audiophonicsonoff-plugin-master/README.md  
  inflating: volumio-audiophonicsonoff-plugin-master/UIConfig.json  
  inflating: volumio-audiophonicsonoff-plugin-master/config.json  
   creating: volumio-audiophonicsonoff-plugin-master/i18n/
  inflating: volumio-audiophonicsonoff-plugin-master/i18n/strings_en.json  
   creating: volumio-audiophonicsonoff-plugin-master/images/
  inflating: volumio-audiophonicsonoff-plugin-master/images/settings.png  
  inflating: volumio-audiophonicsonoff-plugin-master/index.js  
  inflating: volumio-audiophonicsonoff-plugin-master/install.sh  
  inflating: volumio-audiophonicsonoff-plugin-master/package.json  
  inflating: volumio-audiophonicsonoff-plugin-master/uninstall.sh  
  inflating: volumio-audiophonicsonoff-plugin-master/volumio-audiophonicsonoff-plugin.zip  
volumio@volumio:~$ ls
Q2M
volumio-audiophonicsonoff-plugin-master
volumio-audiophonicsonoff-plugin-master.zip
volumio@volumio:~$ cd volumio-audiophonicsonoff-plugin-master
volumio@volumio:~/volumio-audiophonicsonoff-plugin-master$ ls
LICENSE        config.json  index.js      uninstall.sh
README.md      i18n         install.sh    volumio-audiophonicsonoff-plugin.zip
UIConfig.json  images       package.json
volumio@volumio:~/volumio-audiophonicsonoff-plugin-master$ volumio plugin install

This command will install the plugin on your device

Compressing the plugin
No modules found, running "npm install"
npm notice created a lockfile as package-lock.json. You should commit this file.
Plugin succesfully compressed
/bin/mv: target '/tmp/plugins/audiophonicsonoff.zip' is not a directory
child_process.js:644
    throw err;
    ^

Error: Command failed: /bin/mv *.zip /tmp/plugins/audiophonicsonoff.zip
/bin/mv: target '/tmp/plugins/audiophonicsonoff.zip' is not a directory

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at install (/volumio/pluginhelper.js:688:9)
    at Object.<anonymous> (/volumio/pluginhelper.js:749:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
volumio@volumio:~/volumio-audiophonicsonoff-plugin-master$ ls
LICENSE                i18n          package-lock.json
README.md              images        package.json
UIConfig.json          index.js      uninstall.sh
audiophonicsonoff.zip  install.sh    volumio-audiophonicsonoff-plugin.zip
config.json            node_modules
volumio@volumio:~/volumio-audiophonicsonoff-plugin-master$ npm i
up to date in 1.431s
volumio@volumio:~/volumio-audiophonicsonoff-plugin-master$ volumio plugin install

This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
/bin/mv: target '/tmp/plugins/audiophonicsonoff.zip' is not a directory
child_process.js:644
    throw err;
    ^

Error: Command failed: /bin/mv *.zip /tmp/plugins/audiophonicsonoff.zip
/bin/mv: target '/tmp/plugins/audiophonicsonoff.zip' is not a directory

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at install (/volumio/pluginhelper.js:688:9)
    at Object.<anonymous> (/volumio/pluginhelper.js:749:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
volumio@volumio:~/volumio-audiophonicsonoff-plugin-master$ ls
LICENSE                i18n          package-lock.json
README.md              images        package.json
UIConfig.json          index.js      uninstall.sh
audiophonicsonoff.zip  install.sh    volumio-audiophonicsonoff-plugin.zip
config.json            node_modules

```


Thats what happened so far
I would really appreciate some help as the machine is not half the fun without your plugin!

AtB
Martin

**Comment by audiophonics** [comment]
> Btw, the step-by-step is as follows:
> 
> 1. download the zip
> 2. unzip it
> 3. install build-essential (apt-get update && apt-get install -y build-essential)
> 4. execute "npm i" while in the directory
> 5. execute "volumio plugin install"

Worked fine. Thanks for the update !
I added these steps to the install procedure in our Power management repository manual.

**Comment by Saiyato** [comment]
Awesome, you're welcome :)

@audiomartin  does this solve your problem as well?
@Alien8ions same goes for you, installing the 'new way' should solve your issues.

**Comment by audiomartin** [comment]
Hi all, during the weekend i already made it running, with the help of the old installing advises from audiophonics gitsource. Worked with 2.457. Maybe because i tried the other steps before?

`mkdir ./audiophonicsonoff-plugin
wget https://github.com/Saiyato/volumio-audiophonicsonoff-plugin/raw/master/volumio-audiophonicsonoff-plugin.zip
miniunzip volumio-audiophonicsonoff-plugin.zip -d ./audiophonicsonoff-plugin
cd ./audiophonicsonoff-plugin
volumio plugin install`

So my Audiophonics ES9028 is running as it should again.
Thanks all!

Audiomartin

**Comment by Saiyato** [comment]
@Alien8ions you seem to still have problems, can you confirm this?
Also can you give us your step-by-step and/or try my updated one?

Thanks

**Comment by Alien8ions** [comment]
Nope
`volumio-audiophonicsonoff-plugin-master.zip                                          
volumio@volumioii:~$ unzip volumio-audiophonicsonoff-plugin-master.zip               
-bash: unzip: command not found                                                      
volumio@volumioii:~$ miniunzip volumio-audiophonicsonoff-plugin-master.zip           
MiniUnz 1.01b, demo of zLib + Unz package written by Gilles Vollant                  
more info at http://www.winimage.com/zLibDll/unzip.html                              
                                                                                     
volumio-audiophonicsonoff-plugin-master.zip opened                                   
creating directory: volumio-audiophonicsonoff-plugin-master/                         
 extracting: volumio-audiophonicsonoff-plugin-master/.gitattributes                  
 extracting: volumio-audiophonicsonoff-plugin-master/LICENSE                         
 extracting: volumio-audiophonicsonoff-plugin-master/README.md                       
 extracting: volumio-audiophonicsonoff-plugin-master/UIConfig.json                   
 extracting: volumio-audiophonicsonoff-plugin-master/config.json                     
creating directory: volumio-audiophonicsonoff-plugin-master/i18n/                    
 extracting: volumio-audiophonicsonoff-plugin-master/i18n/strings_en.json            
creating directory: volumio-audiophonicsonoff-plugin-master/images/                  
 extracting: volumio-audiophonicsonoff-plugin-master/images/settings.png             
 extracting: volumio-audiophonicsonoff-plugin-master/index.js                        
 extracting: volumio-audiophonicsonoff-plugin-master/install.sh                      
 extracting: volumio-audiophonicsonoff-plugin-master/package.json                    
 extracting: volumio-audiophonicsonoff-plugin-master/uninstall.sh                    
 extracting: volumio-audiophonicsonoff-plugin-master/volumio-audiophonicsonoff-plugin
.zip                                                                                 
volumio@volumioii:~$ ls                                                              
volumio-audiophonicsonoff-plugin-master  volumio-audiophonicsonoff-plugin-master.zip 
volumio@volumioii:~$ cd volumio-audiophonicsonoff-plugin-master                      
volumio@volumioii:~/volumio-audiophonicsonoff-plugin-master$ ls                      
LICENSE        config.json  index.js      uninstall.sh                               
README.md      i18n         install.sh    volumio-audiophonicsonoff-plugin.zip       
UIConfig.json  images       package.json                                             
volumio@volumioii:~/volumio-audiophonicsonoff-plugin-master$ sudo apt-get update && a
pt-get install -y build-essential                                                    
Hit http://archive.volumio.org jessie InRelease                                      
Hit http://archive.volumio.org jessie InRelease                                      
Hit http://archive.volumio.org jessie/main Sources                                   
Hit http://archive.volumio.org jessie/contrib Sources                                
Hit http://archive.volumio.org jessie/non-free Sources                               
Hit http://archive.volumio.org jessie/rpi Sources                                    
Hit http://archive.volumio.org jessie/main armhf Packages                            
Hit http://archive.volumio.org jessie/contrib armhf Packages                         
Hit http://archive.volumio.org jessie/non-free armhf Packages                        
Hit http://archive.volumio.org jessie/rpi armhf Packages                             
Hit http://archive.volumio.org jessie/main Sources                                   
Hit http://archive.volumio.org jessie/ui Sources                                     
Hit http://archive.volumio.org jessie/main armhf Packages                            
Hit http://archive.volumio.org jessie/ui armhf Packages                              
Ign http://archive.volumio.org jessie/contrib Translation-en                         
Ign http://archive.volumio.org jessie/main Translation-en                            
Ign http://archive.volumio.org jessie/non-free Translation-en                        
Ign http://archive.volumio.org jessie/rpi Translation-en                             
Ign http://archive.volumio.org jessie/main Translation-en                            
Ign http://archive.volumio.org jessie/ui Translation-en                              
Reading package lists... Done                                                        
Reading package lists... Done                                                        
Building dependency tree                                                             
Reading state information... Done                                                    
build-essential is already the newest version.                                       
0 upgraded, 0 newly installed, 0 to remove and 55 not upgraded.                              

volumio@volumioii:~/volumio-audiophonicsonoff-plugin-master$ npm i                   
                                                                                     
> epoll@1.0.2 install /home/volumio/volumio-audiophonicsonoff-plugin-master/node_modu
les/epoll                                                                            
> node-gyp rebuild                                                                   
                                                                                     
make: Entering directory '/home/volumio/volumio-audiophonicsonoff-plugin-master/node_
modules/epoll/build'                                                                 
  CXX(target) Release/obj.target/epoll/src/epoll.o                                   
  SOLINK_MODULE(target) Release/obj.target/epoll.node                                
  COPY Release/epoll.node                                                            
make: Leaving directory '/home/volumio/volumio-audiophonicsonoff-plugin-master/node_m
odules/epoll/build'                                                                  
npm notice created a lockfile as package-lock.json. You should commit this file.     
added 30 packages in 43.879s                                                         
                                                                                     
                                                                                     
   ╭───────────────────────────────────╮                                             
   │                                     │                                           
   │   Update available 5.6.0 → 6.4.1    │                                           
   │     Run npm i -g npm to update      │                                           
   │                                     │                                           
   ╰───────────────────────────────────╯                                             
                                                                                     
volumio@volumioii:~/volumio-audiophonicsonoff-plugin-master$ volumio plugin install  
                                                                                     
This command will install the plugin on your device                                  
                                                                                     
Compressing the plugin                                                               
Plugin succesfully compressed                                                        
/bin/mv: target '/tmp/plugins/audiophonicsonoff.zip' is not a directory              
child_process.js:644                                                                 
    throw err;                                                                       
    ^                                                                                
                                                                                     
Error: Command failed: /bin/mv *.zip /tmp/plugins/audiophonicsonoff.zip              
/bin/mv: target '/tmp/plugins/audiophonicsonoff.zip' is not a directory              
                                                                                     
    at checkExecSyncError (child_process.js:601:13)                                  
    at execSync (child_process.js:641:13)                                            
    at install (/volumio/pluginhelper.js:688:9)                                      
    at Object.<anonymous> (/volumio/pluginhelper.js:749:9)                           
    at Module._compile (module.js:652:30)                                            
    at Object.Module._extensions..js (module.js:663:10)                              
    at Module.load (module.js:565:32)                                                
    at tryModuleLoad (module.js:505:12)                                              
    at Function.Module._load (module.js:497:3)                                       
    at Function.Module.runMain (module.js:693:10)                                    
volumio@volumioii:~/volumio-audiophonicsonoff-plugin-master$`

I uninstalled this plugin after a working one just for you to be able to test it, so here goes :-(

Upgraded to last version of volumio btw, took the plugin from the github website as is
Diego

**Comment by Saiyato** [comment]
I think the problem is that you're downloading the entire repo, you only need _volumio-audiophonicsonoff-plugin.zip_; unzip that and run npm i

**Comment by Alien8ions** [comment]
`volumio@volumioii:~$ cp /mnt/INTERNAL/volumio-audiophonicsonoff-plugin.zip .         
volumio@volumioii:~$ ls                                                              
volumio-audiophonicsonoff-plugin.zip                                                 
volumio@volumioii:~$ miniunzip volumio-audiophonicsonoff-plugin.zip                  
MiniUnz 1.01b, demo of zLib + Unz package written by Gilles Vollant                  
more info at http://www.winimage.com/zLibDll/unzip.html                              
                                                                                     
volumio-audiophonicsonoff-plugin.zip opened                                          
 extracting: config.json                                                             
 extracting: index.js                                                                
 extracting: install.sh                                                              
 extracting: package.json                                                            
 extracting: UIConfig.json                                                           
 extracting: uninstall.sh                                                            
creating directory: i18n/                                                            
 extracting: i18n/strings_en.json                                                    
volumio@volumioii:~$ ls                                                              
UIConfig.json  i18n      install.sh    uninstall.sh                                  
config.json    index.js  package.json  volumio-audiophonicsonoff-plugin.zip          
volumio@volumioii:~$ npm i                                                           
                                                                                     
> epoll@1.0.2 install /home/volumio/node_modules/epoll                               
> node-gyp rebuild                                                                   
                                                                                     
make: Entering directory '/home/volumio/node_modules/epoll/build'                    
  CXX(target) Release/obj.target/epoll/src/epoll.o                                   
  SOLINK_MODULE(target) Release/obj.target/epoll.node                                
  COPY Release/epoll.node                                                            
make: Leaving directory '/home/volumio/node_modules/epoll/build'                     
npm notice created a lockfile as package-lock.json. You should commit this file.     
added 29 packages in 29.465s                                                         
volumio@volumioii:~$ volumio plugin install                                          
                                                                                     
This command will install the plugin on your device                                  
                                                                                     
Compressing the plugin                                                               
Plugin succesfully compressed                                                        
/bin/mv: target '/tmp/plugins/audiophonicsonoff.zip' is not a directory              
child_process.js:644                                                                 
    throw err;                                                                       
    ^                                                                                
                                                                                     
Error: Command failed: /bin/mv *.zip /tmp/plugins/audiophonicsonoff.zip              
/bin/mv: target '/tmp/plugins/audiophonicsonoff.zip' is not a directory              
                                                                                     
    at checkExecSyncError (child_process.js:601:13)                                  
    at execSync (child_process.js:641:13)                                            
    at install (/volumio/pluginhelper.js:688:9)                                      
    at Object.<anonymous> (/volumio/pluginhelper.js:749:9)                           
    at Module._compile (module.js:652:30)                                            
    at Object.Module._extensions..js (module.js:663:10)                              
    at Module.load (module.js:565:32)                                                
    at tryModuleLoad (module.js:505:12)                                              
    at Function.Module._load (module.js:497:3)                                       
    at Function.Module.runMain (module.js:693:10)                                    
volumio@volumioii:~$                                                                 
`


Nope, unless there lives another version
Diego

**Comment by Saiyato** [comment]
I think you forget to remove the zipfile, this is where your installation fails. 

Try this:

1. download zip
2. unzip
**3. remove the zip file you downloaded**
4. install build-essential (if not already done, otherwise skip this step)
5. npm i
6. volumio plugin install

```
volumio@volumiotest:~$ wget -O volumio-audiophonics-plugin.zip https://github.com/Saiyato/volumio-audiophonicsonoff-plugin/blob/master/volumio-audiophonicsonoff-plugin.zip?raw=true
converted 'https://github.com/Saiyato/volumio-audiophonicsonoff-plugin/blob/master/volumio-audiophonicsonoff-plugin.zip?raw=true' (ANSI_X3.4-1968) -> 'https://github.com/Saiyato/volumio-audiophonicsonoff-plugin/blob/master/volumio-audiophonicsonoff-plugin.zip?raw=true' (UTF-8)
--2018-10-02 15:35:46--  https://github.com/Saiyato/volumio-audiophonicsonoff-plugin/blob/master/volumio-audiophonicsonoff-plugin.zip?raw=true
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/Saiyato/volumio-audiophonicsonoff-plugin/raw/master/volumio-audiophonicsonoff-plugin.zip [following]
converted 'https://github.com/Saiyato/volumio-audiophonicsonoff-plugin/raw/master/volumio-audiophonicsonoff-plugin.zip' (ANSI_X3.4-1968) -> 'https://github.com/Saiyato/volumio-audiophonicsonoff-plugin/raw/master/volumio-audiophonicsonoff-plugin.zip' (UTF-8)
--2018-10-02 15:35:47--  https://github.com/Saiyato/volumio-audiophonicsonoff-plugin/raw/master/volumio-audiophonicsonoff-plugin.zip
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Saiyato/volumio-audiophonicsonoff-plugin/master/volumio-audiophonicsonoff-plugin.zip [following]
converted 'https://raw.githubusercontent.com/Saiyato/volumio-audiophonicsonoff-plugin/master/volumio-audiophonicsonoff-plugin.zip' (ANSI_X3.4-1968) -> 'https://raw.githubusercontent.com/Saiyato/volumio-audiophonicsonoff-plugin/master/volumio-audiophonicsonoff-plugin.zip' (UTF-8)
--2018-10-02 15:35:47--  https://raw.githubusercontent.com/Saiyato/volumio-audiophonicsonoff-plugin/master/volumio-audiophonicsonoff-plugin.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4422 (4.3K) [application/zip]
Saving to: 'volumio-audiophonics-plugin.zip'

volumio-audiophonics-plugin.zip      100%[========================================================================>]   4.32K  --.-KB/s   in 0.001s

2018-10-02 15:35:47 (5.05 MB/s) - 'volumio-audiophonics-plugin.zip' saved [4422/4422]
volumio@volumiotest:~$ miniunzip -xo volumio-audiophonics-plugin.zip
MiniUnz 1.01b, demo of zLib + Unz package written by Gilles Vollant
more info at http://www.winimage.com/zLibDll/unzip.html

volumio-audiophonics-plugin.zip opened
 extracting: config.json
 extracting: index.js
 extracting: install.sh
 extracting: package.json
 extracting: UIConfig.json
 extracting: uninstall.sh
creating directory: i18n/
 extracting: i18n/strings_en.json
volumio@volumiotest:~$ rm volumio-audiophonics-plugin.zip
volumio@volumiotest:~$ sudo apt-get update && apt-get install -y build-essential
Hit http://archive.raspbian.org jessie InRelease
Hit http://archive.raspberrypi.org jessie InRelease
Get:1 http://archive.raspbian.org jessie/main Sources [7759 kB]
Hit http://archive.raspberrypi.org jessie/main Sources
Hit http://archive.raspberrypi.org jessie/ui Sources
Hit http://archive.raspberrypi.org jessie/main armhf Packages
Hit http://archive.raspberrypi.org jessie/ui armhf Packages
Ign http://archive.raspberrypi.org jessie/main Translation-en
Ign http://archive.raspberrypi.org jessie/ui Translation-en
Get:2 http://archive.raspbian.org jessie/contrib Sources [64.5 kB]
Get:3 http://archive.raspbian.org jessie/non-free Sources [113 kB]
Get:4 http://archive.raspbian.org jessie/rpi Sources [1132 B]
Hit http://archive.raspbian.org jessie/main armhf Packages
Hit http://archive.raspbian.org jessie/contrib armhf Packages
Hit http://archive.raspbian.org jessie/non-free armhf Packages
Hit http://archive.raspbian.org jessie/rpi armhf Packages
Ign http://archive.raspbian.org jessie/contrib Translation-en
Ign http://archive.raspbian.org jessie/main Translation-en
Ign http://archive.raspbian.org jessie/non-free Translation-en
Ign http://archive.raspbian.org jessie/rpi Translation-en
Fetched 7938 kB in 38s (204 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 130 not upgraded.

volumio@volumiotest:~$ npm i

> epoll@1.0.2 install /home/volumio/node_modules/epoll
> node-gyp rebuild

make: Entering directory '/home/volumio/node_modules/epoll/build'
  CXX(target) Release/obj.target/epoll/src/epoll.o
  SOLINK_MODULE(target) Release/obj.target/epoll.node
  COPY Release/epoll.node
make: Leaving directory '/home/volumio/node_modules/epoll/build'
audiophonicsonoff@1.0.2 /home/volumio
+-- balanced-match@1.0.0
+-- bindings@1.3.0
+-- brace-expansion@1.1.11
+-- concat-map@0.0.1
+-- epoll@1.0.2
| `-- nan@2.8.0
+-- fs-extra@0.28.0
+-- fs.realpath@1.0.0
+-- glob@7.1.3
+-- graceful-fs@4.1.11
+-- imurmurhash@0.1.4
+-- inflight@1.0.6
+-- inherits@2.0.3
+-- jsonfile@2.4.0
+-- kew@0.7.0
+-- klaw@1.3.1
+-- minimatch@3.0.4
+-- multimap@1.0.2
+-- net@1.0.2
+-- once@1.4.0
+-- onoff@1.2.0
+-- path-is-absolute@1.0.1
+-- rimraf@2.6.2
+-- slide@1.1.6
+-- v-conf@1.4.2
| +-- fs-extra@2.1.2
| `-- write-file-atomic@1.3.1
+-- wrappy@1.0.2
`-- write-file-atomic@1.3.4

volumio@volumiotest:~$ volumio plugin install

This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin
Progress: 30
Status :Creating folder on disk
Progress: 40
Status :Unpacking plugin
Progress: 50
Status :Checking for duplicate plugin
Progress: 60
Status :Copying Plugin into location
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 90
Status :Adding plugin to registry
Progress: 100
Status :Plugin Successfully Installed
Done!
```

**Comment by Saiyato** [comment]
Oh and clean up afterwards, otherwise your home dir is full of unnecessary files, you might want to unzip to a subdir to prevent pollution of your home dir...

**Comment by Alien8ions** [comment]
Works with the new and improved instructions.

I was diligently following the directions.
Foolproof now
Diego

**Comment by Saiyato** [comment]
Awesome, thanks for the feedback!

**Comment by cs2ea** [comment]
Thank you for the update and instructions - worked fine!  I was disappointed when the plugin stopped working after upgrading volumio and very grateful to see the fix
