### ISSUE TITLE
Cannot open volumio-audiophonicsonoff-plugin.zip

### ISSUE THREAD

**Issue by sonnenkind78** [Saiyato/volumio-audiophonicsonoff-plugin#3]
Hi.

I have troubles to unzip the plugin.

This is whats happening:
----------------------------------------------------
**volumio@volumio:~$ wget https://github.com/Saiyato/volumio-audiophonicsonoff-plugin/blob/master/volumio-audiophonicsonoff-plugin.zip
converted 'https://github.com/Saiyato/volumio-audiophonicsonoff-plugin/blob/master/volumio-audiophonicsonoff-plugin.zip' (ANSI_X3.4-1968) -> 'https://github.com/Saiyato/volumio-audiophonicsonoff-plugin/blob/master/volumio-audiophonicsonoff-plugin.zip' (UTF-8)
--2018-10-06 15:21:15--  https://github.com/Saiyato/volumio-audiophonicsonoff-plugin/blob/master/volumio-audiophonicsonoff-plugin.zip
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'volumio-audiophonicsonoff-plugin.zip'

volumio-audiophonic     [ <=>                  ]  39.24K   198KB/s   in 0.2s   

2018-10-06 15:21:15 (198 KB/s) - 'volumio-audiophonicsonoff-plugin.zip' saved [40181]

volumio@volumio:~$ mkdir ./volaudiophonicsonoff
volumio@volumio:~$ miniunzip volumio-audiophonicsonoff-plugin.zip -d ./volaudiophonicsonoff
MiniUnz 1.01b, demo of zLib + Unz package written by Gilles Vollant
more info at http://www.winimage.com/zLibDll/unzip.html

Cannot open volumio-audiophonicsonoff-plugin.zip or volumio-audiophonicsonoff-plugin.zip.zip**
------------------------------------------

I tried different folders and ways, but nothing helps I f i open the zip file on the mac, it works fine.

Im using volumio version 2.457 with a raspberry pi 3 B+

Hope you can help. Thanks

**Comment by Saiyato** [comment]
You're not downloading the zip file, download this: https://github.com/Saiyato/volumio-audiophonicsonoff-plugin/raw/master/volumio-audiophonicsonoff-plugin.zip
